import Link from "next/link";

import { CompetitorMonitorAlertList } from "@/components/competitor-monitor/alert-list";
import {
  CompetitorMonitorMetricCard,
  CompetitorMonitorSectionCard,
  CompetitorMonitorStatusBadge,
} from "@/components/competitor-monitor/primitives";
import {
  formatCompetitorMonitorCompactNumber,
  formatCompetitorMonitorCurrency,
  formatCompetitorMonitorDateTime,
} from "@/lib/competitor-monitor/formatters";
import { competitorMonitorClient } from "@/lib/competitor-monitor/client";
import { competitorMonitorRoutes } from "@/lib/competitor-monitor/routes";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export default async function CompetitorMonitorDashboardPage() {
  const { data, meta } = await competitorMonitorClient.getDashboard();

  return (
    <>
      <section className="grid gap-4 xl:grid-cols-4">
        {data.metrics.map(({ key, ...metric }) => (
          <CompetitorMonitorMetricCard key={key} {...metric} />
        ))}
      </section>

      <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
        <CompetitorMonitorSectionCard
          eyebrow="Data layer"
          title="The UI is now wired to the real competitor-monitor backend."
          description={`View-models are generated from the repository-backed service layer. Payload refreshed at ${formatCompetitorMonitorDateTime(
            meta.generatedAt
          )}.`}
        >
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="rounded-[1.4rem] border border-slate-200 bg-white/85 px-4 py-4">
              <p className="section-kicker">API namespace</p>
              <p className="mt-2 text-lg font-semibold text-slate-950">
                /api/competitor-monitor/*
              </p>
              <p className="mt-2 text-sm leading-7 text-slate-600">
                Dashboard, markets, ASIN detail, alerts, and sync routes remain
                under the real backend contract.
              </p>
            </div>
            <div className="rounded-[1.4rem] border border-slate-200 bg-white/85 px-4 py-4">
              <p className="section-kicker">Storage</p>
              <p className="mt-2 text-lg font-semibold text-slate-950">
                Repository + sync services
              </p>
              <p className="mt-2 text-sm leading-7 text-slate-600">
                UI pages read through an adapter layer instead of importing mock
                payloads or parallel types.
              </p>
            </div>
            <div className="rounded-[1.4rem] border border-slate-200 bg-white/85 px-4 py-4">
              <p className="section-kicker">Alerts</p>
              <p className="mt-2 text-lg font-semibold text-slate-950">
                Real snapshot diffs
              </p>
              <p className="mt-2 text-sm leading-7 text-slate-600">
                Price, rating, review, and BSR changes surface directly from the
                alert service instead of mocked thresholds.
              </p>
            </div>
          </div>
        </CompetitorMonitorSectionCard>

        <CompetitorMonitorSectionCard
          eyebrow="Recent alerts"
          title="Signals that need the next operator pass"
          description="These cards now come from the real alert stream, scoped to the current repository data."
          action={
            <Link
              href={competitorMonitorRoutes.alerts}
              className="inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-slate-800"
            >
              Open alert center
            </Link>
          }
        >
          <CompetitorMonitorAlertList
            alerts={data.recentAlerts.slice(0, 4)}
            emptyText="No recent alerts were generated by the current repository data."
          />
        </CompetitorMonitorSectionCard>
      </section>

      <CompetitorMonitorSectionCard
        eyebrow="Market snapshot"
        title="Watchlists currently configured in the repository"
        description="Cards keep the UI layout from the frontend thread, but the values now reflect stored market detail and sync coverage."
      >
        <div className="grid gap-4 xl:grid-cols-3">
          {data.markets.map((market) => (
            <article
              key={market.marketId}
              className="rounded-[1.6rem] border border-slate-200 bg-white/85 p-5 shadow-[0_16px_36px_rgba(16,32,51,0.05)]"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <p className="section-kicker">
                    {market.countryCode} / {market.region}
                  </p>
                  <h3 className="mt-2 text-xl font-semibold text-slate-950">
                    {market.marketName}
                  </h3>
                </div>
                <CompetitorMonitorStatusBadge kind="health" value={market.health} />
              </div>

              <dl className="mt-5 grid gap-3 text-sm text-slate-600">
                <div className="flex items-center justify-between gap-3">
                  <dt>Tracked ASINs</dt>
                  <dd className="font-semibold text-slate-950">{market.asinCount}</dd>
                </div>
                <div className="flex items-center justify-between gap-3">
                  <dt>Sync coverage</dt>
                  <dd className="font-semibold text-slate-950">
                    {market.coverageRate.toFixed(0)}%
                  </dd>
                </div>
                <div className="flex items-center justify-between gap-3">
                  <dt>Open alerts</dt>
                  <dd className="font-semibold text-slate-950">
                    {market.activeAlertCount}
                  </dd>
                </div>
                <div className="flex items-center justify-between gap-3">
                  <dt>Avg price</dt>
                  <dd className="font-semibold text-slate-950">
                    {market.averagePrice !== null
                      ? formatCompetitorMonitorCurrency(
                          market.averagePrice,
                          market.currency
                        )
                      : "Not synced"}
                  </dd>
                </div>
              </dl>

              <p className="mt-5 rounded-[1.3rem] bg-slate-50 px-4 py-3 text-sm leading-7 text-slate-600">
                {market.description}
              </p>

              <div className="mt-5 flex items-center justify-between gap-3">
                <Link
                  href={competitorMonitorRoutes.marketDetail(market.marketId)}
                  className="text-sm font-semibold text-slate-950 hover:text-slate-700"
                >
                  View market detail
                </Link>
                <span className="text-sm text-slate-500">
                  {market.heroAsin ?? "No hero ASIN yet"}
                </span>
              </div>
            </article>
          ))}
        </div>
      </CompetitorMonitorSectionCard>

      <CompetitorMonitorSectionCard
        eyebrow="Priority ASINs"
        title="Rows with the most immediate monitoring pressure"
        description="These rows are ranked from the real market detail payloads, using alert load first and recency second."
      >
        {data.priorityAsins.length > 0 ? (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>ASIN</TableHead>
                <TableHead>Market</TableHead>
                <TableHead>Health</TableHead>
                <TableHead>Price</TableHead>
                <TableHead>Rating</TableHead>
                <TableHead>Reviews</TableHead>
                <TableHead>Alerts</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {data.priorityAsins.map((asin) => (
                <TableRow key={`${asin.marketId}-${asin.asin}`}>
                  <TableCell>
                    <Link
                      href={competitorMonitorRoutes.asinDetail(asin.asin)}
                      className="font-semibold text-slate-950 hover:text-slate-700"
                    >
                      {asin.asin}
                    </Link>
                    <p className="mt-1 max-w-[22rem] text-xs whitespace-normal text-slate-500">
                      {asin.title}
                    </p>
                  </TableCell>
                  <TableCell>{asin.marketName}</TableCell>
                  <TableCell>
                    <CompetitorMonitorStatusBadge kind="health" value={asin.health} />
                  </TableCell>
                  <TableCell>
                    {asin.price !== null
                      ? formatCompetitorMonitorCurrency(asin.price, asin.currency)
                      : "Pending"}
                  </TableCell>
                  <TableCell>
                    {asin.rating !== null ? asin.rating.toFixed(1) : "Pending"}
                  </TableCell>
                  <TableCell>
                    {formatCompetitorMonitorCompactNumber(asin.reviewCount)}
                  </TableCell>
                  <TableCell>{asin.alertCount}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <div className="rounded-[1.5rem] border border-dashed border-slate-300 bg-slate-50 px-5 py-8 text-sm leading-7 text-slate-500">
            No tracked ASIN rows are ready to rank yet. Run a sync after markets
            are configured to populate this table.
          </div>
        )}
      </CompetitorMonitorSectionCard>
    </>
  );
}
